//
//  WeatherData.m
//  mid-unit-2-assessment
//
//  Created by Michael Kavouras on 10/4/15.
//  Copyright © 2015 Michael Kavouras. All rights reserved.
//

#import "WeatherData.h"

@implementation WeatherData





+ (NSArray *)allData {
    NSArray *info = @[
                      @{
                          @"time": @1443931200,
                          @"summary": @"Mostly cloudy throughout the day.",
                          @"icon": @"partly-cloudy-day",
                          @"sunriseTime": @1443956172,
                          @"sunsetTime": @1443998115,
                          @"moonPhase": @(0.74),
                          @"precipIntensity": @(0.0002),
                          @"precipIntensityMax": @(0.0011),
                          @"precipIntensityMaxTime": @1444003200,
                          @"precipProbability": @(0.01),
                          @"precipType": @"rain",
                          @"temperatureMin": @(51.75),
                          @"temperatureMinTime": @1443963600,
                          @"temperatureMax": @(57.78),
                          @"temperatureMaxTime": @1443985200,
                          @"apparentTemperatureMin": @(51.75),
                          @"apparentTemperatureMinTime": @1443963600,
                          @"apparentTemperatureMax": @(57.78),
                          @"apparentTemperatureMaxTime": @1443985200,
                          @"dewPoint": @(46.17),
                          @"humidity": @(0.73),
                          @"windSpeed": @(12.62),
                          @"windBearing": @38,
                          @"visibility": @(9.71),
                          @"cloudCover": @(0.85),
                          @"pressure": @(1025.53),
                          @"ozone": @(256.09)
                          },
                      @{
                          @"time": @1444017600,
                          @"summary": @"Mostly cloudy until evening.",
                          @"icon": @"partly-cloudy-day",
                          @"sunriseTime": @1444042634,
                          @"sunsetTime": @1444084416,
                          @"moonPhase": @(0.77),
                          @"precipIntensity": @0,
                          @"precipIntensityMax": @0,
                          @"precipProbability": @0,
                          @"temperatureMin": @(49.91),
                          @"temperatureMinTime": @1444042800,
                          @"temperatureMax": @(63.09),
                          @"temperatureMaxTime": @1444075200,
                          @"apparentTemperatureMin": @(45.18),
                          @"apparentTemperatureMinTime": @(1444042800),
                          @"apparentTemperatureMax": @(63.09),
                          @"apparentTemperatureMaxTime": @(1444075200),
                          @"dewPoint": @(48.95),
                          @"humidity": @(0.77),
                          @"windSpeed": @(10.84),
                          @"windBearing": @15,
                          @"visibility": @(9.84),
                          @"cloudCover": @(0.69),
                          @"pressure": @(1021.03),
                          @"ozone": @(257.57)
                          },
                      @{
                          @"time":                       @1444104000,
                          @"summary":                    @"Partly cloudy until afternoon.",
                          @"icon":                       @"partly-cloudy-day",
                          @"sunriseTime":                @1444129095,
                          @"sunsetTime":                 @1444170717,
                          @"moonPhase":                  @0.81,
                          @"precipIntensity":            @0,
                          @"precipIntensityMax":         @0,
                          @"precipProbability":          @0,
                          @"temperatureMin":             @50.74,
                          @"temperatureMinTime":         @1444129200,
                          @"temperatureMax":             @70.03,
                          @"temperatureMaxTime":         @1444161600,
                          @"apparentTemperatureMin":     @50.74,
                          @"apparentTemperatureMinTime": @1444129200,
                          @"apparentTemperatureMax":     @70.03,
                          @"apparentTemperatureMaxTime": @1444161600,
                          @"dewPoint":                   @49.25,
                          @"humidity":                   @0.69,
                          @"windSpeed":                  @4.99,
                          @"windBearing":                @327,
                          @"visibility":                 @10,
                          @"cloudCover":                 @0.2,
                          @"pressure":                   @1016.19,
                          @"ozone":                      @261.32
                          },
                      @{
                          @"time":                       @1444190400,
                          @"summary":                    @"Clear throughout the day.",
                          @"icon":                       @"clear-day",
                          @"sunriseTime":                @1444215557,
                          @"sunsetTime":                 @1444257019,
                          @"moonPhase":                  @0.84,
                          @"precipIntensity":            @0,
                          @"precipIntensityMax":         @0,
                          @"precipProbability":          @0,
                          @"temperatureMin":             @54.33,
                          @"temperatureMinTime":         @1444215600,
                          @"temperatureMax":             @73.52,
                          @"temperatureMaxTime":         @1444248000,
                          @"apparentTemperatureMin":     @54.33,
                          @"apparentTemperatureMinTime": @1444215600,
                          @"apparentTemperatureMax":     @73.52,
                          @"apparentTemperatureMaxTime": @1444248000,
                          @"dewPoint":                   @53.71,
                          @"humidity":                   @0.7,
                          @"windSpeed":                  @7.63,
                          @"windBearing":                @309,
                          @"visibility":                 @10,
                          @"cloudCover":                 @0.03,
                          @"pressure":                   @1015.03,
                          @"ozone":                      @277.66
                          },
                      @{
                          @"time":                       @1444276800,
                          @"summary":                    @"Partly cloudy overnight.",
                          @"icon":                       @"partly-cloudy-night",
                          @"sunriseTime":                @1444302019,
                          @"sunsetTime":                 @1444343322,
                          @"moonPhase":                  @0.87,
                          @"precipIntensity":            @0,
                          @"precipIntensityMax":         @0,
                          @"precipProbability":          @0,
                          @"temperatureMin":             @56.26,
                          @"temperatureMinTime":         @1444305600,
                          @"temperatureMax":             @63.76,
                          @"temperatureMaxTime":         @1444276800,
                          @"apparentTemperatureMin":     @56.26,
                          @"apparentTemperatureMinTime": @1444305600,
                          @"apparentTemperatureMax":     @63.76,
                          @"apparentTemperatureMaxTime": @1444276800,
                          @"dewPoint":                   @44.61,
                          @"humidity":                   @0.58,
                          @"windSpeed":                  @6.78,
                          @"windBearing":                @36,
                          @"cloudCover":                 @0.03,
                          @"pressure":                   @1022.4,
                          @"ozone":                      @287.71
                          },
                      @{
                          @"time":                       @1444363200,
                          @"summary":                    @"Rain starting in the evening.",
                          @"icon":                       @"rain",
                          @"sunriseTime":                @1444388482,
                          @"sunsetTime":                 @1444429625,
                          @"moonPhase":                  @0.9,
                          @"precipIntensity":            @0.0058,
                          @"precipIntensityMax":         @0.0626,
                          @"precipIntensityMaxTime":     @1444446000,
                          @"precipProbability":          @0.64,
                          @"precipType":                 @"rain",
                          @"temperatureMin":             @61.83,
                          @"temperatureMinTime":         @1444392000,
                          @"temperatureMax":             @68.63,
                          @"temperatureMaxTime":         @1444435200,
                          @"apparentTemperatureMin":     @61.83,
                          @"apparentTemperatureMinTime": @1444392000,
                          @"apparentTemperatureMax":     @68.63,
                          @"apparentTemperatureMaxTime": @1444435200,
                          @"dewPoint":                   @55.44,
                          @"humidity":                   @0.71,
                          @"windSpeed":                  @11.98,
                          @"windBearing":                @201,
                          @"cloudCover":                 @0.64,
                          @"pressure":                   @1019.31,
                          @"ozone":                      @294.62
                          },
                      @{
                          @"time":                       @1444449600,
                          @"summary":                    @"Mostly cloudy until afternoon.",
                          @"icon":                       @"partly-cloudy-day",
                          @"sunriseTime":                @1444474945,
                          @"sunsetTime":                 @1444515929,
                          @"moonPhase":                  @0.93,
                          @"precipIntensity":            @0.0081,
                          @"precipIntensityMax":         @0.0599,
                          @"precipIntensityMaxTime":     @1444449600,
                          @"precipProbability":          @0.63,
                          @"precipType":                 @"rain",
                          @"temperatureMin":             @59.08,
                          @"temperatureMinTime":         @1444485600,
                          @"temperatureMax":             @65.4,
                          @"temperatureMaxTime":         @1444510800,
                          @"apparentTemperatureMin":     @59.08,
                          @"apparentTemperatureMinTime": @1444485600,
                          @"apparentTemperatureMax":     @65.4,
                          @"apparentTemperatureMaxTime": @1444510800,
                          @"dewPoint":                   @53.02,
                          @"humidity":                   @0.72,
                          @"windSpeed":                  @8.41,
                          @"windBearing":                @352,
                          @"cloudCover":                 @0.51,
                          @"pressure":                   @1016.03,
                          @"ozone":                      @309.93
                          },
                      @{
                          @"time":                       @1444536000,
                          @"summary":                    @"Partly cloudy starting in the afternoon.",
                          @"icon":                       @"partly-cloudy-night",
                          @"sunriseTime":                @1444561408,
                          @"sunsetTime":                 @1444602234,
                          @"moonPhase":                  @0.96,
                          @"precipIntensity":            @0.0013,
                          @"precipIntensityMax":         @0.0032,
                          @"precipIntensityMaxTime":     @1444543200,
                          @"precipProbability":          @0.1,
                          @"precipType":                 @"rain",
                          @"temperatureMin":             @56.89,
                          @"temperatureMinTime":         @1444618800,
                          @"temperatureMax":             @64.07,
                          @"temperatureMaxTime":         @1444586400,
                          @"apparentTemperatureMin":     @56.89,
                          @"apparentTemperatureMinTime": @1444618800,
                          @"apparentTemperatureMax":     @64.07,
                          @"apparentTemperatureMaxTime": @1444586400,
                          @"dewPoint":                   @49.24,
                          @"humidity":                   @0.66,
                          @"windSpeed":                  @11.25,
                          @"windBearing":                @297,
                          @"cloudCover":                 @0.31,
                          @"pressure":                   @1012.06,
                          @"ozone":                      @315.42
                          }
                      ];
    return info;
}

@end
